Add Xdebug support

diff --git a/php-fpm/xdebug b/php-fpm/xdebug
--- a/php-fpm/xdebug
+++ b/php-fpm/xdebug
@@ -1,32 +1,9 @@
 #! /bin/bash
 
-# NOTE: At the moment, this has only been confirmed to work with PHP 7
-
-
-# Grab full name of php-fpm container
-PHP_FPM_CONTAINER=$(docker ps | grep php-fpm | awk '{print $1}')
-
-
-# Grab OS type
-if [[ "$(uname)" == "Darwin" ]]; then
-    OS_TYPE="OSX"
-else
-    OS_TYPE=$(expr substr $(uname -s) 1 5)
-fi
-
-
 xdebug_status ()
 {
     echo 'xDebug status'
-
-    # If running on Windows, need to prepend with winpty :(
-    if [[ $OS_TYPE == "MINGW" ]]; then
-        winpty docker exec -it $PHP_FPM_CONTAINER bash -c 'php -v'
-
-    else
-        docker exec -it $PHP_FPM_CONTAINER bash -c 'php -v'
-    fi
-
+    docker exec -it $PHP_FPM_CONTAINER bash -c 'php -m | grep xdebug'
 }
 
 
@@ -36,20 +13,11 @@ xdebug_start ()
 
     # And uncomment line with xdebug extension, thus enabling it
     ON_CMD="sed -i 's/^;zend_extension=/zend_extension=/g' \
-                    /usr/local/etc/php/conf.d/xdebug.ini"
+                    /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
 
-
-    # If running on Windows, need to prepend with winpty :(
-    if [[ $OS_TYPE == "MINGW" ]]; then
-        winpty docker exec -it $PHP_FPM_CONTAINER bash -c "${ON_CMD}"
-        docker restart $PHP_FPM_CONTAINER
-        winpty docker exec -it $PHP_FPM_CONTAINER bash -c 'php -v'
-
-    else
-        docker exec -it $PHP_FPM_CONTAINER bash -c "${ON_CMD}"
-        docker restart $PHP_FPM_CONTAINER
-        docker exec -it $PHP_FPM_CONTAINER bash -c 'php -v'
-    fi
+    docker exec -it $PHP_FPM_CONTAINER bash -c "${ON_CMD}"
+    docker restart $PHP_FPM_CONTAINER
+    xdebug_status
 }
 
 
@@ -58,29 +26,34 @@ xdebug_stop ()
     echo 'Stop xDebug'
 
     # Comment out xdebug extension line
-    OFF_CMD="sed -i 's/^zend_extension=/;zend_extension=/g' /usr/local/etc/php/conf.d/xdebug.ini"
+    OFF_CMD="sed -i 's/^zend_extension=/;zend_extension=/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
 
-
-    # If running on Windows, need to prepend with winpty :(
-    if [[ $OS_TYPE == "MINGW" ]]; then
-        # This is the equivalent of:
-        # winpty docker exec -it laradock_php-fpm_1 bash -c 'bla bla bla'
-        # Thanks to @michaelarnauts at https://github.com/docker/compose/issues/593
-        winpty docker exec -it $PHP_FPM_CONTAINER bash -c "${OFF_CMD}"
-        docker restart $PHP_FPM_CONTAINER
-        #docker-compose restart php-fpm
-        winpty docker exec -it $PHP_FPM_CONTAINER bash -c 'php -v'
-
-    else
-        docker exec -it $PHP_FPM_CONTAINER bash -c "${OFF_CMD}"
-        # docker-compose restart php-fpm
-        docker restart $PHP_FPM_CONTAINER
-        docker exec -it $PHP_FPM_CONTAINER bash -c 'php -v'
-    fi
+    docker exec -it $PHP_FPM_CONTAINER bash -c "${OFF_CMD}"
+    # docker-compose restart php-fpm
+    docker restart $PHP_FPM_CONTAINER
+    xdebug_status
 }
 
+help()
+{
+    echo "xDebug [Stop | Start | Status] in the php-fpm container."
+    echo "Usage:"
+    echo "  .php-fpm/xdebug stop|start|status 81|82|83"
+}
 
-case $@ in
+if [ -z ${1+x} ] || [ -z ${2+x} ]; then
+  help
+  exit 1
+fi
+
+PHP_FPM_CONTAINER=$(docker ps | grep php${2}-fpm | awk '{print $1}')
+
+if [ -z "${PHP_FPM_CONTAINER}" ]; then
+  echo "Running container for PHP version ${2} was not found"
+  exit 1
+fi
+
+case $1 in
     stop|STOP)
         xdebug_stop
         ;;
@@ -91,11 +64,7 @@ case $@ in
         xdebug_status
         ;;
     *)
-        echo "xDebug [Stop | Start | Status] in the ${PHP_FPM_CONTAINER} container."
-        echo "xDebug must have already been installed."
-        echo "Usage:"
-        echo "  .php-fpm/xdebug stop|start|status"
-
+        help
 esac
 
 exit 1
