command enhancement
- delete old xdebug command
- add command to enter php container

diff --git a/laradock b/laradock
--- a/laradock
+++ b/laradock
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-find_running_php_fpm_container () {
+find_running_php_fpm_container() {
   local container=$(docker ps | grep laradock-lite-php${1}-fpm | awk '{print $1}')
 
   if [ -z "${container}" ]; then
@@ -28,64 +28,102 @@ xdebug() {
 
   if [[ $? -ne 0 ]]; then
     echo $PHP_FPM_CONTAINER
-    exit 1;
+    exit 1
   fi
 
   case $2 in
-    stop|STOP)
-        xdebug_stop
-        ;;
-    start|START)
-        xdebug_start
-        ;;
-    status|STATUS)
-        xdebug_status
-        ;;
+    stop | STOP)
+      xdebug_stop
+      ;;
+    start | START)
+      xdebug_start
+      ;;
+    status | STATUS)
+      xdebug_status
+      ;;
     *)
-        echo "Unrecognized argument"
-        echo "---"
-        xdebug_help
+      echo "Unrecognized argument"
+      echo "---"
+      xdebug_help
+      ;;
   esac
 }
 
-xdebug_status ()
-{
-    echo 'xDebug status'
-    docker exec -it $PHP_FPM_CONTAINER bash -c 'php -m | grep xdebug'
+xdebug_status() {
+  echo 'xDebug status'
+  docker exec -it $PHP_FPM_CONTAINER bash -c 'php -m | grep xdebug'
 }
 
-xdebug_start ()
-{
-    echo 'Start xDebug'
+xdebug_start() {
+  echo 'Start xDebug'
 
-    # And uncomment line with xdebug extension, thus enabling it
-    ON_CMD="sed -i 's/^;zend_extension=/zend_extension=/g' \
+  # And uncomment line with xdebug extension, thus enabling it
+  ON_CMD="sed -i 's/^;zend_extension=/zend_extension=/g' \
                     /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
 
-    docker exec -it $PHP_FPM_CONTAINER bash -c "${ON_CMD}"
-    docker restart $PHP_FPM_CONTAINER
-    xdebug_status
+  docker exec -it $PHP_FPM_CONTAINER bash -c "${ON_CMD}"
+  docker restart $PHP_FPM_CONTAINER
+  xdebug_status
 }
 
+xdebug_stop() {
+  echo 'Stop xDebug'
 
-xdebug_stop ()
-{
-    echo 'Stop xDebug'
+  # Comment out xdebug extension line
+  OFF_CMD="sed -i 's/^zend_extension=/;zend_extension=/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
 
-    # Comment out xdebug extension line
-    OFF_CMD="sed -i 's/^zend_extension=/;zend_extension=/g' /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"
-
-    docker exec -it $PHP_FPM_CONTAINER bash -c "${OFF_CMD}"
-    # docker-compose restart php-fpm
-    docker restart $PHP_FPM_CONTAINER
-    xdebug_status
+  docker exec -it $PHP_FPM_CONTAINER bash -c "${OFF_CMD}"
+  # docker-compose restart php-fpm
+  docker restart $PHP_FPM_CONTAINER
+  xdebug_status
 }
 
-xdebug_help()
-{
-    echo "xDebug [Stop | Start | Status] in the php-fpm container."
-    echo "Usage:"
-    echo " ./laradock xdebug stop|start|status 81|82|83"
+xdebug_help() {
+  echo "xDebug [stop | start | status] in the php container."
+  echo "Usage:"
+  echo " ./laradock xdebug stop|start|status 81|82|83"
+}
+
+php() {
+  if [ -z ${2+x} ] || [ ${2} == "help" ]; then
+    php_help
+    exit 1
+  fi
+
+  if [ -z ${2+x} ] || [ -z ${3+x} ]; then
+    echo "Missing required argument."
+    echo "---"
+    php_help
+    exit 1
+  fi
+
+  PHP_FPM_CONTAINER=$(find_running_php_fpm_container $3 2>&1)
+
+  if [[ $? -ne 0 ]]; then
+    echo $PHP_FPM_CONTAINER
+    exit 1
+  fi
+
+  case $2 in
+    enter | ENTER)
+      php_enter
+      ;;
+    *)
+      echo "Unrecognized argument"
+      echo "---"
+      php_help
+      ;;
+  esac
+}
+
+php_enter() {
+  docker exec -u www-data -it $PHP_FPM_CONTAINER bash
+}
+
+php_help() {
+  echo "php [enter] in the php container"
+  echo "Usage:"
+  echo " ./laradock php enter 81|82|83"
 }
 
 help() {
@@ -94,11 +132,15 @@ help() {
 }
 
 case $1 in
-    xdebug)
-        xdebug $@
-        ;;
-    *)
-        help
+  xdebug)
+    xdebug $@
+    ;;
+  php)
+    php $@
+    ;;
+  *)
+    help
+    ;;
 esac
 
-exit 1
+exit 0
